block.settings.jumper_block:
  type: block_settings
  label: 'Jumper block settings'
  mapping:
    target:
      type: string
      label: Target
    duration:
      type: integer
      label: Duration
    offset:
      type: integer
      label: Offset
    color:
      type: string
      label: 'Background color'
    no_text:
      type: boolean
      label: 'Visually hide the title text'
    selectors:
      type: string
      label: 'Additional selectors'
    style:
      type: string
      label: Style
    text:
      type: string
      label: Text
    visibility:
      type: integer
      label: Visibility
    autovlm:
      type: boolean
      label: 'Auto trigger View Load More'
